### ISSUE TITLE
Exception when saving.

### ISSUE THREAD

**Issue by shwork96** [mikaelnet/Sitecore.RelNoOpener#1]
When installed in 8.1 it throws an exception when saving a change. The event log shows that there is an exception in the pipeline but not what the actual exception is. The site core log shows the dll and config are loading. I know this is vague but are there any known issues with the code?

**Comment by mikaelnet** [comment]
This might have been caused by an assembly binding issue with `HtmlAgilityPack`. I noticed I used a later version of it than the one that comes as default in Sitecore 8.1. I've downgraded it to 1.4.6 (default in Sitecore 8.1 update 3), but you can also add an assembly binding directive in your web.config to solve this.

If your error was caused by something else, please provide me with the details from the Sitecore log files.

**Comment by shwork96** [comment]
It’s working now. As you suggested, I removed the  Nuget HtmlAgilityPack and Sitecore.Kernel.dll packages and removed the reference to htlmagility in the web.config. I’m using the HtmlAgilityPack dll and the Sitecore.Kernel.dll from my Sitecore instance instead.

Thanks,
Scott
